/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalpro;

/**
 *
 * @author Widi
 */
public class bayarBelanja extends javax.swing.JFrame {

    /**
     * Creates new form bayarBelanja
     */
    
    public bayarBelanja(String total) {
        initComponents();
        totalBelanja.setText(total);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textField1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        uangBayar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel = new javax.swing.JLabel();
        bayar = new javax.swing.JButton();
        totalBelanja = new javax.swing.JLabel();
        kembalian = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(207, 245, 195));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setText("Nominal Belanja");

        textField1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        textField1.setText("Rp");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setText("Uang di Bayar");

        uangBayar.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        uangBayar.setMargin(new java.awt.Insets(2, 10, 2, 2));
        uangBayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                uangBayarKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel4.setText("Kembalian");

        jLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel.setText("Rp");

        bayar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bayar.setText("BAYAR");

        totalBelanja.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        totalBelanja.setText("0");

        kembalian.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        kembalian.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(textField1)
                        .addGap(18, 18, 18)
                        .addComponent(totalBelanja))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel)
                        .addGap(18, 18, 18)
                        .addComponent(kembalian))
                    .addComponent(uangBayar))
                .addContainerGap(150, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textField1)
                    .addComponent(totalBelanja))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(uangBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel)
                    .addComponent(kembalian))
                .addGap(18, 18, 18)
                .addComponent(bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void uangBayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uangBayarKeyReleased
        // TODO add your handling code here:
        if(uangBayar.getText().length()>=3){
            float kembali = Float.parseFloat(uangBayar.getText()) - Float.parseFloat(totalBelanja.getText());
            kembalian.setText(Float.toString(kembali));
        }
    }//GEN-LAST:event_uangBayarKeyReleased

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton bayar;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    protected javax.swing.JLabel kembalian;
    private javax.swing.JLabel textField1;
    private javax.swing.JLabel totalBelanja;
    protected javax.swing.JTextField uangBayar;
    // End of variables declaration//GEN-END:variables
}
