/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalpro;

import javax.swing.JOptionPane;

/**
 *
 * @author Widi
 */
public class registerUser extends javax.swing.JFrame {

    /**
     * Creates new form registerUser
     */
    protected String username, nama, tgl, jk, loyal, alamat;
    public registerUser() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tambahUserPanel = new javax.swing.JPanel();
        tambahUserTxt = new javax.swing.JLabel();
        usernameUserText = new javax.swing.JLabel();
        usernameUserTextField = new javax.swing.JTextField();
        namaUserText = new javax.swing.JLabel();
        namaUserTextField = new javax.swing.JTextField();
        tglLahirUserText = new javax.swing.JLabel();
        tglLahirUserTextField = new javax.swing.JTextField();
        alamatUserText = new javax.swing.JLabel();
        alamatUserTextField = new javax.swing.JTextField();
        JKUserText = new javax.swing.JLabel();
        JKUserCombobox = new javax.swing.JComboBox<>();
        tambahDataUserButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tambahUserPanel.setBackground(new java.awt.Color(41, 128, 185));
        tambahUserPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        tambahUserTxt.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        tambahUserTxt.setForeground(new java.awt.Color(255, 255, 255));
        tambahUserTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tambahUserTxt.setText("Tambah Data User");

        usernameUserText.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        usernameUserText.setForeground(new java.awt.Color(255, 255, 255));
        usernameUserText.setText("Username");

        usernameUserTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        namaUserText.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        namaUserText.setForeground(new java.awt.Color(255, 255, 255));
        namaUserText.setText("Nama Lengkap");

        namaUserTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tglLahirUserText.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        tglLahirUserText.setForeground(new java.awt.Color(255, 255, 255));
        tglLahirUserText.setText("Tanggal Lahir");

        tglLahirUserTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        alamatUserText.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        alamatUserText.setForeground(new java.awt.Color(255, 255, 255));
        alamatUserText.setText("Alamat");

        JKUserText.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        JKUserText.setForeground(new java.awt.Color(255, 255, 255));
        JKUserText.setText("Jenis Kelamin");

        JKUserCombobox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JKUserCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jenis Kelamin...", "Laki-laki", "Perempuan" }));
        JKUserCombobox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tambahDataUserButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tambahDataUserButton.setText("Simpan");

        javax.swing.GroupLayout tambahUserPanelLayout = new javax.swing.GroupLayout(tambahUserPanel);
        tambahUserPanel.setLayout(tambahUserPanelLayout);
        tambahUserPanelLayout.setHorizontalGroup(
            tambahUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahUserPanelLayout.createSequentialGroup()
                .addGroup(tambahUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tambahUserPanelLayout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(tambahUserTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tambahUserPanelLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(tambahUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(tambahUserPanelLayout.createSequentialGroup()
                                .addComponent(usernameUserText, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(usernameUserTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tambahUserPanelLayout.createSequentialGroup()
                                .addComponent(namaUserText, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(namaUserTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tambahUserPanelLayout.createSequentialGroup()
                                .addComponent(tglLahirUserText, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tglLahirUserTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tambahUserPanelLayout.createSequentialGroup()
                                .addComponent(alamatUserText, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(alamatUserTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tambahUserPanelLayout.createSequentialGroup()
                                .addComponent(JKUserText, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JKUserCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(156, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tambahUserPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tambahDataUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        tambahUserPanelLayout.setVerticalGroup(
            tambahUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahUserPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tambahUserTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(tambahUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameUserTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameUserText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tambahUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaUserTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaUserText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(tambahUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tglLahirUserTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tglLahirUserText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tambahUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alamatUserTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alamatUserText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tambahUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JKUserCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JKUserText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(tambahDataUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 729, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(tambahUserPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(tambahUserPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    protected int cek(){
        username = usernameUserTextField.getText();
        nama = namaUserTextField.getText();
        tgl = tglLahirUserTextField.getText();
        alamat = alamatUserTextField.getText();
        jk = JKUserCombobox.getSelectedItem().toString();
        if(username.isEmpty() || nama.isEmpty() || tgl.isEmpty() || alamat.isEmpty() || JKUserCombobox.getSelectedIndex()==0)
            JOptionPane.showMessageDialog(null, "ISIKAN SEMUA FIELD");
        else{
            try{
                koneksi data = new koneksi();
                String sql = "SELECT username FROM user WHERE username='" + username + "'";
                data.rs = data.st.executeQuery(sql);
                if(data.rs.next()){
                    JOptionPane.showMessageDialog(null, "Username Sudah Ada");
                }else{
                    data.tutupKoneksi();
                    return 1;
                }
                data.tutupKoneksi();
            }catch(Exception e){
                System.out.println(e.getMessage());
            }
            
            
        }
        return 0;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JKUserCombobox;
    private javax.swing.JLabel JKUserText;
    private javax.swing.JLabel alamatUserText;
    private javax.swing.JTextField alamatUserTextField;
    private javax.swing.JLabel namaUserText;
    private javax.swing.JTextField namaUserTextField;
    protected javax.swing.JButton tambahDataUserButton;
    private javax.swing.JPanel tambahUserPanel;
    private javax.swing.JLabel tambahUserTxt;
    private javax.swing.JLabel tglLahirUserText;
    private javax.swing.JTextField tglLahirUserTextField;
    private javax.swing.JLabel usernameUserText;
    private javax.swing.JTextField usernameUserTextField;
    // End of variables declaration//GEN-END:variables
}
