/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalpro;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Widi
 */
public class userkasir extends javax.swing.JFrame {

    /**
     * Creates new form userkasir
     */    
    public userkasir() {
        initComponents();
        setResizable(false);
        cariUserNama.requestFocus();
        koneksi data = new koneksi();
        DefaultTableModel tabel = (DefaultTableModel) userCariTabel.getModel();
        try{
            String sql = "SELECT * FROM user";
            data.rs = data.st.executeQuery(sql);
            while(data.rs.next()){
                Object[] row = {data.rs.getString("username"),data.rs.getString("nama"),data.rs.getString("tgl_lahir"),data.rs.getString("loyal")};
                tabel.addRow(row);
            }
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cariUserNama = new javax.swing.JTextField();
        belanjaButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        userCariTabel = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel1.setText("CARI USER");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setText("Nama");

        cariUserNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cariUserNamaKeyReleased(evt);
            }
        });

        belanjaButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        belanjaButton.setText("Belanja");

        userCariTabel.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        userCariTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Nama", "Tgl Lahir", "Loyal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        userCariTabel.setRowHeight(25);
        userCariTabel.setRowMargin(5);
        userCariTabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userCariTabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(userCariTabel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cariUserNama, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(belanjaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel1)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(belanjaButton, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(cariUserNama))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cariUser(String nama){
        try{
            DefaultTableModel tabel = (DefaultTableModel) userCariTabel.getModel();
            tabel.setRowCount(0);
            koneksi data = new koneksi();
            String sql = "SELECT * FROM user WHERE nama LIKE '%" + nama + "%'";
            data.rs = data.st.executeQuery(sql);
            while(data.rs.next()){
                String namaU = data.rs.getString("nama");
                String username = data.rs.getString("username");
                String tgl = data.rs.getString("tgl_lahir");
                String loyal = data.rs.getString("loyal");
                Object[] row = {username, namaU, tgl, loyal};
                tabel.addRow(row);
            }
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }
    
    private void cariUserNamaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariUserNamaKeyReleased
        // TODO add your handling code here:
        cariUser(cariUserNama.getText());
    }//GEN-LAST:event_cariUserNamaKeyReleased

    private void userCariTabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userCariTabelMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 2){
            cariUserNama.setText(userCariTabel.getValueAt(userCariTabel.getSelectedRow(), 1).toString());
            cariUser(cariUserNama.getText());
        }
    }//GEN-LAST:event_userCariTabelMouseClicked

    
    
    protected int cekField(){
        if(cariUserNama.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "MASUKKAN NAMA DULU");
            cariUserNama.requestFocus();
        }else if(userCariTabel.getRowCount() == 0){
            JOptionPane.showMessageDialog(null, "NAMA TIDAK ADA YANG SESUAI");
            cariUserNama.requestFocus();
        }else if(userCariTabel.getRowCount() > 1){
            JOptionPane.showMessageDialog(null, "PILIH NAMA YANG SESUAI");
            cariUserNama.requestFocus();
        }else if(!cariUserNama.getText().equals(userCariTabel.getValueAt(0, 1))){
            JOptionPane.showMessageDialog(null, "KETIKKAN NAMA YANG BENAR");
            cariUserNama.requestFocus();
        }else if(userCariTabel.getRowCount() == 1)
            return 1;
        return 0;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton belanjaButton;
    protected javax.swing.JTextField cariUserNama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JTable userCariTabel;
    // End of variables declaration//GEN-END:variables
}
